name: SEO Checker

on:
  # push:
    # branches:
      # - main   # Trigger action on push to the main branch (you can adjust as needed)
  workflow_dispatch:  # Allows manual trigger
jobs:
  seo-check:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu environment

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # You can change the Node version if needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install axios cheerio jsdom crypto
      # Step 4: Run the SEO checker script
      - name: Run SEO Checker
        run: |
          node seoChecker.js
          
      # Step 5: Upload SEO Check Results as Artifacts (Optional)
      - name: Upload SEO Check Results
        uses: actions/upload-artifact@v3
        with:
          name: seo-check-results
          path: ./seo-check-results.txt
